#pragma once

#define SEAD_VERSION_NONE      0
#define SEAD_VERSION_REDPEPPER 1
#define SEAD_VERSION_CTRDASH   2

#ifndef SEAD_VERSION
#define SEAD_VERSION SEAD_VERSION_REDPEPPER /* Default */
#endif

/// sead version features:
///
/// SEAD_THREADMGR_MOVED_SINGLETON_DISPOSER:
///     Moves ThreadMgr's singleton disposer to the end of the class
/// SEAD_HEAP_FREEANDGETALLOCATABLESIZE_VIRTUAL:
///     Adds freeAndGetAllocatableSize virtual to Heap
/// SEAD_RTTI_CHECKDERIVEDRUNTIMETYPEINFO_RETURNS_INSTANCE:
///     Makes checkDerivedRuntimeTypeInfo return the object instance instead of a boolean
/// SEAD_THREAD_GETFIBER:
///     Adds virtual getFiber to Thread (and removes getStackCheckStartAddress_)
/// SEAD_DELEGATE_ISNODUMMY:
///     Add isNoDummy() and operator bool() to Delegates
/// SEAD_FRAMEBUFFER_BINDCLEAR_UNBIND
///     Add bindClear_() and unbindImpl_() to FrameBuffer

/* TODO RESEARCH ON */

#if SEAD_VERSION == SEAD_VERSION_REDPEPPER
#define SEAD_THREADMGR_MOVED_SINGLETON_DISPOSER 1
#define SEAD_HEAP_FREEANDGETALLOCATABLESIZE_VIRTUAL 0
#define SEAD_RTTI_CHECKDERIVEDRUNTIMETYPEINFO_RETURNS_INSTANCE 0
#define SEAD_THREAD_GETFIBER 0
#define SEAD_DELEGATE_ISNODUMMY 0
#define SEAD_FRAMEBUFFER_BINDCLEAR_UNBIND 0
#elif SEAD_VERSION == SEAD_VERSION_CTRDASH
#define SEAD_THREADMGR_MOVED_SINGLETON_DISPOSER 0
#define SEAD_HEAP_FREEANDGETALLOCATABLESIZE_VIRTUAL 0
#define SEAD_RTTI_CHECKDERIVEDRUNTIMETYPEINFO_RETURNS_INSTANCE 0
#define SEAD_THREAD_GETFIBER 0
#define SEAD_DELEGATE_ISNODUMMY 0
#define SEAD_FRAMEBUFFER_BINDCLEAR_UNBIND 0
#elif SEAD_VERSION == SEAD_VERSION_NONE
#define SEAD_THREADMGR_MOVED_SINGLETON_DISPOSER 1
#define SEAD_HEAP_FREEANDGETALLOCATABLESIZE_VIRTUAL 1
#define SEAD_RTTI_CHECKDERIVEDRUNTIMETYPEINFO_RETURNS_INSTANCE 1
#define SEAD_THREAD_GETFIBER 1
#define SEAD_DELEGATE_REMOVE_ISNODUMMY 0
#define SEAD_FRAMEBUFFER_BINDCLEAR_UNBIND 1
#endif

/// feature-specific macros

#if SEAD_SAFESTRING_NONVIRTUAL
#define SEAD_SAFESTRING_VIRTUAL_TOKEN
#define SEAD_SAFESTRING_OVERRIDE_TOKEN
#else
#define SEAD_SAFESTRING_VIRTUAL_TOKEN virtual
#define SEAD_SAFESTRING_OVERRIDE_TOKEN override
#endif
